# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/hlte-common/setup-makefiles.sh

ifeq ($(WITH_TWRP),true)
TARGET_RECOVERY_DEVICE_DIRS += vendor/samsung/hlte-common/proprietary
endif
